AWSTemplateFormatVersion: "2010-09-09"

Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete             #SnapshotもRetainも何かしら残るのでこちらを選択
    Properties:
      AllocatedStorage: '20'               #ストレージ5GiB　MySQLの20GiBは最小サイズ
      DBInstanceClass: db.t2.micro        #記事はdb.t3.mediumだったが変更
      DBParameterGroupName: !Ref DBParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: MySQL
      EngineVersion: 8.0.28              #エンジンバージョン今あるRDSと同じバージョンにしてみた
      MasterUsername: admin
      MasterUserPassword: your_secret  #自分のパスワードを入れるの？
      StorageType: gp2

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: custom subnet group
      SubnetIds:
        - !ImportValue Createprivatesubnet01     #プライベートサブネット1にRDSを作る
        - !ImportValue Createprivatesubnet02     #プライベートサブネット2にRDSを作る合計2コできる

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: custom paramter group
      Family: MySQL8.0           #今使っているRDSと一緒
      Parameters:
        character_set_database: utf8mb4   #UTF-8は文字コード、MB4は動画ファイルの
        character_set_client: utf8mb4
        character_set_connection: utf8mb4
        character_set_results: utf8mb4
        character_set_server: utf8mb4

              
Outputs:
  DBInstanceID:
    Value: !Ref DBInstance
    Export:
      Name: DBInstanceID

