AWSTemplateFormatVersion: "2010-09-09"

 DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot             #入れなくても良い？
    Properties:
      AllocatedStorage: '5'               #ストレージ5GiB　今作っているやつは20Gitになっているので本来は大きかった？
      DBInstanceClass: db.t2.micro        #記事はdb.t3.mediumだったが変更
      DBParameterGroupName: !Ref DBParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: MySQL
      EngineVersion: 8.0.28              #エンジンバージョン今あるRDSと同じバージョンにしてみた
      MasterUsername: admin
      MasterUserPassword: your_secret  #自分のパスワードを入れるの？
      StorageType: gp2

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: custom subnet group
      SubnetIds:
        - subnet-privatesubnet01     #プライベートサブネット1にRDSを作る
        - subnet-privatesubnet02     #プライベートサブネット2にRDSを作る合計2コできる

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: custom paramter group
      Family: MySQL8.0           #今使っているRDSと一緒
      Parameters:
        character_set_database: utf8mb4   #UTF-8は文字を書く時に表示されるヤツ、MB4は動画ファイルの
        character_set_client: utf8mb4
        character_set_connection: utf8mb4
        character_set_results: utf8mb4
        character_set_server: utf8mb4

              
Outputs:
  DBInstanceID:
    Value: !Ref DBInstance
    Export:
      Name: !Sub "${PJPrefix}-${DBInstanceName}-id"

  DBInstanceEndpoint:
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub "${PJPrefix}-${DBInstanceName}-endpoint"

  DBName:
    Value: !Ref DBName
    Export:
      Name: !Sub "${PJPrefix}-${DBInstanceName}-dbname"

